import Head from 'next/head';
import { Header } from '../components/landing';
import {
  LastExamsResolved,
  ExamsList,
  CreateExam,
  GlobalRanking,
} from '../components/home';

const LastExamenResolvedData = [
  {
    name: 'Math',
    creator: 'John Doe',
    questions: 24,
    correctQuestions: 16,
    examId: '34',
  },
  {
    name: 'Math',
    creator: 'John Doe',
    questions: 21,
    correctQuestions: 13,
    examId: '35',
  },
  {
    name: 'Math',
    creator: 'John Doe',
    questions: 20,
    correctQuestions: 14,
    examId: '36',
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-tertiary-light">
        <Header />
        <div className="px-4">
          <div className="max-w-6xl mx-auto grid md:grid-cols-3 lg:grid-cols-4 pb-20 pt-8 gap-y-8 gap-x-8">
            <div className="col-start-1 col-end-3 lg:col-end-4">
              <LastExamsResolved data={LastExamenResolvedData} />
            </div>
            <div className="col-start-1 col-end-3 lg:col-end-4">
              <ExamsList title="Favorites" data={LastExamenResolvedData} />
            </div>
            <div className="col-start-1 col-end-3 lg:col-end-4">
              <ExamsList title="Most Popular" data={LastExamenResolvedData} />
            </div>
            <div className=" max-w-xs mx-auto grid col-span-2 md:col-span-1 gap-8 self-start md:col-start-3 lg:col-start-4 md:row-start-1 md:row-end-4">
              <CreateExam />
              <GlobalRanking />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
